# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Afzal Jasani
tagline:          Just Bloggin Around
description:      Learning and exploring new things
url:              localhost:4000
paginate:         3

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo



# Custom vars
version:          2.0.0