# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title

# Setup
title:            Afzal Jasani
tagline:          
description:      Learning and exploring new things
url:              aj786123.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         3

# Custom vars
version:          2.0.0
collections:
  projects:
    output: true 
  photos:
    output: true  