# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title

# Setup
title:            Afzal Jasani
tagline:          
description:      Stir it up
url:              aj786123.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         3

# Custom vars
version:          2.0.1
collections:
  projects:
    output: true 
  photos:
    output: true  
excerpt_separator: "<!--more-->"
